#image parameters
pixel_to_micron_ratio: 1.0

channel_nuclei: 0  # channel for nuclei, optional
channel_EC_junction: 1  # commonly the VE-cadherin marker
channel_siRNA: 2  # channel for siRNA marker, optional

# segmentation parameters
filter_nuclei: True  # if True, filter out nuclei based on size
nuclei_max_area: 400  # threshold for nuclei segmentation
nuclei_min_area: 100  # minimum size of nuclei in pixels
nuclei_min_intensity: 0.0  # minimum mean vecad_intensity of nuclei

# device geometry or setup

use_automated_segmentation: False # if True, use the segment anything model to segment the device geometry, if False, create a binary mask of the device geometry and add _device_mask to the filename before the filename extension. Example file.tif -> add file_device_mask.tif


# segmentation_parameters

gaussian_sigma: {"EC_junction": 5.0, "siRNA": 5.0}
number_of_vertical_tiles: 1


# network parameters

distance_px: 100  # max distance in pixels for an edge to be included in the network graph



extend_x: 5000
extend_y: 5000

n_sample: 5000


